---
name: CI

on:
  pull_request:
  push:
    branch: master

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: '2.7'
            puppet: 7
          - ruby: '3.2'
            puppet: 8
    env:
      PUPPET_GEM_VERSION: "~> ${{ matrix.puppet }}.0"
    name: "Ruby ${{ matrix.ruby }} with Puppet ${{ matrix.puppet }}"
    steps:
      - uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test
